Set network namespace
Netflix/titus-executor pull request #554
Opened 2021-03-03 06:23 UTC by aloktiagi

This change creates an ipvlan interface in the transition namespace when network system calls need to be intercepted in a container

1. check if network system calls have to be intercepted.
2. create an ipvlan interface in the transition namespace.
3. Assign IPv6 address to the interface in the container's namespace and IPv4 address to the interface in the transition namespace.

2021-03-05 22:38 UTC, solarkennedy requested changes

2021-03-05 22:38 UTC, solarkennedy commented on vpc/tool/container/setup_container_linux.go
> +func getNsFd(netNS interface{}) (int, bool, error) {
This is not very go-like.

Are you sure it isn't simpler to just pass 2 nsfds all the time instead of overloading the `netNS` object?

2021-03-05 22:41 UTC, solarkennedy commented on cmd/titus-vpc-tool/setup_container.go
> +	cmd.Flags().String("transition-netns", "trans-netns", "The name # of the network namespace to setup for transition")
I think the fact that we have an fd above (`3`) and a second thing which is a string which is the name of a namespace, we are setting ourselves up for confusion.

Do we even need it to be a name? Can it be a bool ?

2021-03-05 22:43 UTC, solarkennedy commented on executor/runtime/docker/docker.go
> +				"TITUS_SECCOMP_AGENT_TRANSITION_NETNS":    r.c.TaskID() + "trans-netns",
Do we need this? 
I guess we need to *somehow* tell TSA what to switch into.
Hmm.

2021-03-05 22:48 UTC, solarkennedy requested changes

2021-03-05 22:48 UTC, solarkennedy commented on vpc/tool/container/setup_container_linux.go
> +	if !withTrans || (withTrans && isTransLink) {
This is hard for me to understand.

Could this logic be simplified if these toggles were called `enableIPv4` and `enableIPv6` and let the caller figure out exactly what to pass through, given the transition logic?

2021-03-05 22:48 UTC, solarkennedy commented on vpc/tool/container/setup_container_linux.go
> +		ip := net.ParseIP(allocation.IPV4Address.Address.Address)
If one of the links doesn't have ipv4, does this still work?

2021-03-05 22:48 UTC, solarkennedy commented on vpc/tool/container/setup_container_linux.go
> +	netnsfd, _, err := getNsFd(netNS)
Can we get away with this `deleteLink` function remaining the same as before, just the caller gives it a different fd depending on which link it is deleting?

2021-12-06 17:31 UTC, solarkennedy commented
@aloktiagi can you close this if it is no longer relevant ?

2022-01-25 01:57 UTC, aloktiagi commented
Closing.

2022-01-25 01:57 UTC, closed without merging