Reduce transition namespace assignment
Netflix/titus-executor pull request #967
Opened 2022-09-15 21:01 UTC by jromero-nflx

Limit transition namespace assignment to unique trunk-eni+sg combinations, instead of creating one per branch-eni association

2022-09-16 18:02 UTC, hechaoli requested changes

2022-09-16 23:14 UTC, jromero-nflx commented on vpc/service/generate_assignment_id.go
> +		err := row.Scan(&ass.transitionAssignmentID)
Implemented

2022-09-16 23:14 UTC, jromero-nflx commented on vpc/service/generate_assignment_id.go
> +		"INSERT INTO assignments(branch_eni_association, assignment_id, jumbo, bandwidth, ceil, transition_assignment) VALUES ($2, $2, $3, $4, $5, $6) RETURNING id, jumbo, bandwidth, ceil",
Fixed

2022-09-16 23:14 UTC, jromero-nflx commented on vpc/service/generate_assignment_id.go
> +		row := fastTx.QueryRowContext(ctx, `
Implemented

2022-09-16 23:15 UTC, jromero-nflx commented on vpc/service/generate_assignment_id.go
> +		row := fastTx.QueryRowContext(ctx, `
Killswitch implemented

2022-09-16 23:15 UTC, jromero-nflx commented on vpc/service/generate_assignment_id.go
> +			transitionAssignmentName := fmt.Sprintf("t-%s", uuid.New().String())
Implemented

2022-09-16 23:15 UTC, jromero-nflx commented on vpc/service/generate_assignment_id.go
> +			row := fastTx.QueryRowContext(ctx, "SELECT id, ipv4addr FROM assignments WHERE is_transition_assignment = true AND branch_eni_association = $1", ass.branch.AssociationID)
Removed unused var

2022-09-19 19:06 UTC, jromero-nflx commented on vpc/service/generate_assignment_id.go
> +	bv := []byte(ass.trunk + strings.Join(ass.securityGroups, ""))
Addressed

2022-09-19 19:06 UTC, jromero-nflx commented on vpc/service/generate_assignment_id.go
> +			span.AddAttributes(trace.StringAttribute("transitionAssignmentsExistenceChecked", ass.trunk+"/"+strings.Join(ass.securityGroups, "")))
Addressed

2022-09-19 19:08 UTC, hechaoli approved these changes
LGTM

2022-09-19 19:42 UTC, merged